// src/components/ViewCounter.svelte
<script lang="ts">
  import { onMount } from "svelte";

  let views: number = 0;

  onMount(async () => {
    const pathname = window.location.pathname;
    const api = "/api/pagecount.json?slug=" + pathname;

    fetch(api)
      .then((res) => res.json())
      .then((res) => (views = res.message));
  });
</script>

<p>{views} views</p>

// src/components/ViewCounter.tsx
import { useEffect, useState } from "react";

export default function ViewCounter() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    const pathname = window.location.pathname;
    const api = "/api/pagecount.json?slug=" + pathname;

    fetch(api)
      .then((res) => res.json())
      .then((res) => setCount(res.message));
  }, []);
  return <p>{count} views</p>;
}
